# Generated by Django 4.2.4 on 2023-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_birth_date_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='RUT'),
        ),
    ]
