# Generated by Django 4.2.4 on 2023-11-13 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_usuario_email_remove_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='full_name',
        ),
    ]
