# Generated by Django 4.2.4 on 2023-11-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_user_verif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verif',
        ),
    ]
