# Generated by Django 4.2.4 on 2023-11-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_user_verif'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('P', 'Postulante'), ('E', 'Empleador')], default='P', max_length=10, verbose_name='Rol de usuario'),
            preserve_default=False,
        ),
    ]
