# Generated by Django 4.2.4 on 2023-11-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='yo', max_length=100, verbose_name='Nombre de Usuario'),
            preserve_default=False,
        ),
    ]
