# Generated by Django 4.2.4 on 2023-11-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_replacementrequest_curriculum'),
        ('polls', '0008_user_username'),
    ]

    operations = [
    ]
