# Generated by Django 4.2.4 on 2023-11-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_merge_20231106_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
