# Generated by Django 4.2.4 on 2023-11-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_replacementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='nombre_empresa',
            field=models.CharField(default='Empresa', max_length=40),
            preserve_default=False,
        ),
    ]
