# Generated by Django 4.2.4 on 2023-11-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_replacementrequest_nombre_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementrequest',
            name='desc',
            field=models.TextField(default='Descripcion por defecto, por favor ingrese información del trabajo'),
            preserve_default=False,
        ),
    ]
