# Generated by Django 4.2.4 on 2023-11-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Nombreusuario', max_length=100, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
    ]
