# Generated by Django 4.2.4 on 2023-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_replacementrequest_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementrequest',
            name='idioma_requerido',
            field=models.CharField(blank=True, choices=[('IN', 'Ingles'), ('FR', 'Frances'), ('PO', 'Portugués'), ('AL', 'Alemán'), ('IT', 'Italiano')], max_length=30, null=True, verbose_name='Idioma'),
        ),
    ]
