# Generated by Django 4.2.4 on 2023-11-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_replacementrequest_gender_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementrequest',
            name='ano_exp',
            field=models.IntegerField(verbose_name='Años de experiencia requeridos'),
        ),
    ]
