# Generated by Django 4.2.4 on 2023-11-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_education_fecha_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementrequest',
            name='cargo',
            field=models.CharField(max_length=40, verbose_name='Cargo del trabajo'),
        ),
    ]
