# Generated by Django 4.2.4 on 2023-11-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_replacementrequest_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementrequest',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de inicio del trabajo'),
        ),
    ]
